services:
  razor-pages:
    image: razor-pages
    build:
      context: .
      dockerfile: razor-pages/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - keys-volume:/app/keys

volumes:
  keys-volume: